import type { NextPage } from 'next';
import Head from 'next/head';

import { useRouter } from 'next/router'

import Product from '@/template/Product/Product';
import { DUMMY_ITEMS } from '@/DB/fake';


const ProductPage: NextPage = () => {
  const router = useRouter();
  const { pid } = router.query;
  const selectedItem = DUMMY_ITEMS.find(item => item.id === pid);
  const frequentItems = DUMMY_ITEMS.filter(item => item.id !== pid);
  const similarItems = frequentItems;
 

  return (
      <>
        <Head>
          <title>Ecommerce - Product</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      {selectedItem && (
        <Product
          title={selectedItem.title}
          image={selectedItem.image}
          price={selectedItem.price}
          oldPrice={selectedItem.oldPrice}
          description="blah blah"
          category={selectedItem.category}
          catSlug={selectedItem.catSlug}
          tags="1,2,3"
          frequentItems={frequentItems}
          similarItems={similarItems}
        />
        )
      }
      </>
    )
  }

export default ProductPage
 