import type { NextPage } from 'next';
import Head from 'next/head';

import { useRouter } from 'next/router'

import Category from '@/template/Category/Category';
import { DUMMY_ITEMS } from '@/DB/fake';


const CategoryPage: NextPage = () => {
  const router = useRouter();
  const { category } = router.query;
  const categoryItems = DUMMY_ITEMS.filter(item => item.catSlug == category);
  var categoryName;
  if (categoryItems[0] != null) {
    categoryName = categoryItems[0].category;
  } else {
    categoryName = 'خالی'
  }
  

 

  return (
      <>
        <Head>
          <title>Ecommerce - Category</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      {categoryItems && (
          <Category items={categoryItems} title={categoryName} />
        )
      }
      </>
    )
  }

export default CategoryPage
 