import type { NextPage } from 'next';
import Head from 'next/head';



const SignupPage: NextPage = () => {
    

    return (
        <>
            <Head>
                <title>Ecommerce - Sign up</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
        </>
    )
}

export default SignupPage
 