import type { NextPage } from 'next';
import Head from 'next/head';

import Cart from '@/template/Cart/Cart';
import { DUMMY_ITEMS } from '@/DB/fake';


const CartPage: NextPage = () => {
    
    const cartItems = DUMMY_ITEMS.filter(items => items.catSlug == 'supermarket');

    return (
        <>
            <Head>
                <title>Ecommerce - Cart</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            {cartItems && (
                <Cart items={cartItems} />
                )
            }
        </>
    )
}

export default CartPage
 