import type { NextPage } from 'next';
import Head from 'next/head';

// Import page layout
import Storefront from '@/template/Home/Storefront';

import {DUMMY_SLIDES, DUMMY_CATEGORIES, DUMMY_ITEMS, DUMMY_SPECIAL_ITEMS, DUMMY_SPECIAL_ITEMS_2 } from '@/DB/fake';


const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Ecommerce - SuperMarket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Storefront categories={DUMMY_CATEGORIES} slides={DUMMY_SLIDES} items={DUMMY_ITEMS} specialItems={DUMMY_SPECIAL_ITEMS} specialItemsAgain={DUMMY_SPECIAL_ITEMS_2} />
     </>
  )
}

export default Home
